SET SERVEROUTPUT ON;
CREATE OR REPLACE PROCEDURE DELETE_EMPLOYEE(V_DEPT IN EMPLOYEE.DEPT%TYPE)
IS
DeptNotFoundException EXCEPTION;
BEGIN
DELETE FROM EMPLOYEE WHERE DEPT = V_DEPT;
IF SQL%FOUND THEN
DBMS_OUTPUT.PUT_LINE(SQL%ROWCOUNT || ' Employee record(s) got deleted.');
ELSE
RAISE DeptNotFoundException;
END IF;
EXCEPTION
WHEN DeptNotFoundException
THEN
DBMS_OUTPUT.PUT_LINE( 'No Records found.');
END;
/