INSERT INTO RESORT values(1001, 'TREE OF LIFE RESORT', 'KACHERAWALA KOOKAS', 'JAIPUR', 3, 3.8, 2);
INSERT INTO RESORT values(1002, 'PALETTE RESORTS', 'LAKE VIEW ROAD NALLVADU POST', 'PONDICHERRY', 2, 4.3, 2);
INSERT INTO RESORT values(1003, 'GRAND GRT', 'SIR THEAGARAYA RD TNAGAR', 'CHENNAI', 1, 4.4, 1);
INSERT INTO RESORT values(1004, 'GREEN COCONUT', 'EAST COAST ROAD, MAHABALIPURAM', 'CHENNAI', 1, 3.7, 1);
